name = "dftd4"
version = "3.7.0"
license = "LGPL-3.0-or-later"
maintainer = ["@awvwgk"]
author = ["Eike Caldeweyher", "Sebastian Ehlert", "Stefan Grimme"]
description = "Generally Applicable Atomic-Charge Dependent London Dispersion Correction"
keywords = ["quantum-chemistry", "dispersion-correction"]
copyright = "Copyright 2017-2021 E. Caldeweyher, S. Ehlert, S. Grimme"

[build]
link = ["lapack", "blas"]
auto-tests = false

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib.git"
mctc-lib.tag = "HEAD"
multicharge.git = "https://github.com/grimme-lab/multicharge.git"
multicharge.tag = "HEAD"

[dev-dependencies]
mstore.git = "https://github.com/grimme-lab/mstore.git"
mstore.tag = "v0.3.0"

[[test]]
name = "tester"
source-dir = "test/unit"
